import Footer from "./components/Footer";
import Header from "./components/Header";

import './globals.css';


export const metadata = {
    title: 'Pascals Garden',
    description: 'Generated by Next.js',
  }


export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-black text-white min-h-screen flex flex-col items-center justify-center">
                <Header />
                <main className="mt-16 p-4">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
