import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";
import BackToTop from "@/app/components/BackToTop";
import './globals.css';
import { Analytics } from "@vercel/analytics/next"

export const metadata = {
  title: 'Pascals Garden',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 mt-20 sm:mt-16 px-4 sm:px-6 pb-28 sm:pb-32 w-full max-w-7xl mx-auto">
          {children}
        </main>
        <BackToTop />
        <Footer />
        <Analytics />
      </body>
    </html>
  );
} 